# Generated by Django 2.2.4 on 2020-01-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_rename_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.Team', verbose_name='team'),
        ),
    ]
