# Generated by Django 2.2.4 on 2020-05-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_auto_20200131_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team', verbose_name='team'),
        ),
    ]
